language: java
deploy:
  provider: heroku
  app: heroku-pipeline-example
  api_key:
    secure: dWMEKbsDKNtykV+P1vZ69mPkjjrpHcetaoJeBMQCD0xDKgq7MYOFo/1MnpYB+XjCf3UErAQBI+VGxbIVgq4uV2vej2ZgOlhDPp1cmfvlkk6gnpmFzIE4UyXnIaVqSuIVySidqhG6u2l3ed8BG/PXozY4H/j+znoseetPxz/rpCs6rG07msYZiVEm3DPfkEaIFwS+RHGqiu1V5jZA9NLX1BuhwiG5bWK51ZqzJr9RgwesFxaw3dLULq+8tXqL+7RCxSW+PjwQ0/q3b6FRY3THwNpmW44seopWwKQ0q7JmciD6aLAD4PnvgtqA9MXnG45QNK4TSnZtyTfCk1e4irKs6CsytDhJ+8czmj0G3xQVabyg2VUvx6rKfHAGhrrCBiRAOC21LgOvrrAUT4rWaK4j6zfK/g/Z97KcMW/aFBescYCFFZ6cls6Zpc0iwZ/PJoKR51AbMLZZsguWD+Se5YS3hVqZ17UcYjFkXDtyAm1QD7Oaf22nZnRLSldi4JRgc2N/RhLAQYmz5/9y/ithLbING/kUzfSCkH1vy9QpoxIZyJDSsYb7ytXMMaotuh2hyjzAkW85wQfacibEM6wSEMduRhMwgT833nQkoRLJjOgegyVUarjjrAZ/7bKZdl5FhPVKHI6VmmhAn2b9jejgEGoxDFdSLPC27WeKoLsEg5S1Hw8=
