language: java
deploy:
  provider: heroku
  app: heroku-pipeline-example
  api_key:
    secure: ajogh58u1lOvAwCvInI90e40hlfvMlHN3Wenrv1uzkkfHTP5vxABGXfYnz6xI8W6VOKRwvOfaQJuG2hd8pU6MeLPRPJ0oo+hO/8ayt8DP2sAwhKVyUFPAoKQnNglxeY+tBHiOts9gHjeXZ5G45PjoQew5lId1bnNoXjHMEmj0N83CTnI2HGJS1vPi739ldYoDQ7d6KwGnaBVYreu3Qn0c9PGG4FwuCRyT9ZBvDLg+OrtZSfJjZREQASXl02GhZzZ3pb+6flSl7nu9ZR9b3nGE65j6pDmDNpp7aofLiR3zfJZztuayi3+vSClLGb5Ue4tZ6+tSK8Lfj0Ucwjpm5iejQ6RL3jSlnJDqKaue281hsYJhSH9ViXKjjY3ITYpXlM9kA85vaHFY+bZjjXLXD/BVJPVF04kEPzaTZ1ZI62QAkMaiaM7ydxKG4v4YdxzjnaxIOrRKo+83trKVxpPKFTWkhgiK1b5zvAgKOR5gupYaQT77bfu4rg2AyHiPYQNZDgv2jnEcdPfdVKMgyrVJ4Hpl4EHfxzMOS62gi7gizQTsXXf1KE69gYNLiu3KlhMFAXoWp32dNtNcxscH3mck2Yqtm4MR+qo5sLbdVQrJl6itLgIpwYS4I9E1ACRI0dNuPGTArxD/VhEvkZa+TJAeKV9SvCQ3nEE+qlDOmZWKfwsZZE=
