#!/bin/bash
docker build . --tag devopsexam --build-arg JAR_FILE=.target/pgr301-10021-0.0.1-SNAPSHOT.jar
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag devopsexam devopsexam
docker push devopsexam