#!/bin/bash
docker build . --tag myping --build-arg JAR_FILE=./target/demo-0.0.1-SNAPSHOT.jar
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag myping boylan157/myping
docker push boylan157/myping